### ISSUE TITLE
Credential配置问题

### ISSUE THREAD

**Issue by Akityo** [ruanjf/n8n-nodes-dingtalk#2]
好像新版本更新以后，节点配置Credential出现问题，无法进行Credential配置。

<img width="410" alt="image" src="https://github.com/ruanjf/n8n-nodes-dingtalk/assets/16974004/5f7e0a66-9c7c-49b2-b387-41a0ecc972cd">

**Comment by ruanjf** [comment]
@Akityo 请升级到`0.0.5`，重新配置Credential。因为新版Credential规范有调整
