### ISSUE TITLE
国内服务器，docker部署的n8n，好像装不了这插件，不知道是不是网络问题，有没有有解决方法呢

### ISSUE THREAD

**Issue by a877429929** [ruanjf/n8n-nodes-dingtalk#3]

**Comment by ruanjf** [comment]
这个可以配置国内的npm镜像地址[https://npmmirror.com/](https://npmmirror.com/)试试

**Comment by ruanjf** [comment]
这个可以配置国内的npm镜像地址[https://npmmirror.com/](https://npmmirror.com/)试试
